name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: set git global safe directory
        run: |
          pacman -Syu git npm flatpak-builder --noconfirm
          git config --global --add safe.directory $(realpath .)

      - uses: actions/checkout@v4
      
      - name: Install Flatpak SDK and Dependencies
        run: |
          pacman -S flatpak --noconfirm
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08 org.freedesktop.Sdk.Extension.node20//23.08

      - name: build AppImage
        run: |
          npm install
          npm run build -- --linux --publish never
          chmod +x dist/StreamingServiceLauncher_v*_linux.AppImage
        continue-on-error: true
        
      - name: build Flatpak
        run: |
          npm run build:flatpak-bundle
          chmod +x StreamingServiceLauncher_v*.flatpak
        continue-on-error: true

      - name: show files
        run: |
          ls ./dist/StreamingServiceLauncher_v*_linux.AppImage
          ls ./StreamingServiceLauncher_v*.flatpak

      - name: Publish AppImage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StreamingServiceLauncher-AppImage
          path: ./dist/StreamingServiceLauncher_v*_linux.AppImage
          
      - name: Publish Flatpak Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StreamingServiceLauncher-Flatpak
          path: ./StreamingServiceLauncher_v*.flatpak

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - run: mkdir /tmp/artifacts

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/StreamingServiceLauncher-AppImage/StreamingServiceLauncher_v*_linux.AppImage
            /tmp/artifacts/StreamingServiceLauncher-Flatpak/StreamingServiceLauncher_v*.flatpak
          tag_name: ${{ github.ref_name }}
          body: |
            StreamingServiceLauncher Release
          draft: true
          generate_release_notes: true
          prerelease: contains(github.ref, 'pre')
          # Using built-in GITHUB_TOKEN which is automatically available
        env:
          GITHUB_TOKEN: ${{ github.token }}
