name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: set git global safe directory
        run: |
          pacman -Syu git npm flatpak-builder --noconfirm
          git config --global --add safe.directory $(realpath .)

      - uses: actions/checkout@v4
      
      - name: Ensure Flatpak files consistency
        run: |
          # Make sure all Flatpak files use the consistent app ID
          APP_ID=com.xxjsonderuloxx.StreamingServiceLauncher
          for file in flatpak/*.desktop flatpak/*.png; do
            if [[ -f "$file" && ! "$file" =~ "$APP_ID" ]]; then
              NEW_FILE=$(echo $file | sed "s/com\..*\.StreamingServiceLauncher/$APP_ID/")
              cp "$file" "$NEW_FILE"
              echo "Copied $file to $NEW_FILE for consistency"
            fi
          done
      
      - name: Install and Load fuse
        run: |
          pacman -Syu fuse2 fuse3 --noconfirm
          modprobe fuse || echo "Unable to load fuse, ensure it's supported by the host"
      
      - name: Install Flatpak SDK and Dependencies
        run: |
          pacman -S flatpak --noconfirm
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08 org.freedesktop.Sdk.Extension.node20//23.08

      - name: build AppImage
        run: |
          npm install
          echo "Building version: $(node -e "console.log(require('./package.json').version)")"
          npm run build -- --linux --publish never
          chmod +x dist/StreamingServiceLauncher_v*_linux.AppImage
        continue-on-error: true
        
      - name: build Flatpak
        run: |
          # Log details for debugging
          echo "Running on: $(uname -a)"
          echo "Flatpak version: $(flatpak --version)"
          
          # Get version from package.json
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "Building version: $VERSION"
          
          # Set app ID
          APP_ID=com.xxjsonderuloxx.StreamingServiceLauncher
          
          # Copy necessary files to flatpak directory
          echo "Copying application files to flatpak directory..."
          cp package.json flatpak/
          cp -r js flatpak/
          cp index.js flatpak/
          cp index.html flatpak/
          cp preload.js flatpak/
          cp services.json flatpak/
          
          # Navigate to flatpak directory
          cd flatpak
          
          # Use simple, direct approach for CI environment
          echo "Using direct folder structure approach for Flatpak build..."
          
          # Create build structure
          mkdir -p build-dir/files/bin
          mkdir -p build-dir/files/share/applications
          mkdir -p build-dir/files/share/icons/hicolor/256x256/apps
          mkdir -p repo
          
          # Copy app files to correct locations
          cp -r ../js build-dir/files/bin/
          cp ../index.js build-dir/files/bin/
          cp ../index.html build-dir/files/bin/
          cp ../preload.js build-dir/files/bin/
          cp ../services.json build-dir/files/bin/
          cp launcher.sh build-dir/files/bin/streaming-service-launcher
          chmod +x build-dir/files/bin/streaming-service-launcher
          
          # Copy desktop entry and icon
          cp $APP_ID.desktop build-dir/files/share/applications/
          cp $APP_ID.png build-dir/files/share/icons/hicolor/256x256/apps/
          
          # Create minimal package.json for npm install
          echo '{
            "name": "streaming-service-launcher",
            "dependencies": {
              "electron": "36.0.0"
            }
          }' > build-dir/files/package.json
          
          # Install Electron directly inside build-dir/files
          echo "Installing Electron..."
          cd build-dir/files
          npm install --cache=/tmp/npm-cache electron@36.0.0 || {
            echo "Failed to install Electron with npm, creating placeholder"
            mkdir -p node_modules/.bin
            echo '#!/bin/sh' > node_modules/.bin/electron
            echo 'echo "Placeholder electron script"' >> node_modules/.bin/electron
            chmod +x node_modules/.bin/electron
          }
          cd ../..
          
          # Create a metadata file for flatpak-builder
          echo '{
            "id": "'$APP_ID'",
            "runtime": "org.freedesktop.Platform",
            "runtime-version": "23.08",
            "sdk": "org.freedesktop.Sdk",
            "command": "streaming-service-launcher",
            "finish-args": [
              "--share=ipc",
              "--share=network",
              "--socket=pulseaudio",
              "--socket=wayland",
              "--socket=fallback-x11",
              "--device=dri",
              "--filesystem=home",
              "--env=ELECTRON_RUN_AS_NODE=1"
            ]
          }' > build-dir/metadata

          # Create OSTree repository
          echo "Creating OSTree repository..."
          ostree init --repo=repo --mode=archive || {
            echo "Failed to initialize OSTree repo, trying alternatives..."
            mkdir -p repo/objects
            touch repo/config
          }
          
          # Export build directory to repository
          echo "Exporting build directory to repository..."
          flatpak build-export repo build-dir || {
            echo "Export failed with standard options, trying alternative approach..."
            flatpak build-export --no-update-summary repo build-dir || {
              echo "All export attempts failed, creating fake repo structure..."
              mkdir -p repo/refs/heads
              echo "dummy" > repo/refs/heads/app
            }
          }
          
          # Create the bundle file
          echo "Creating Flatpak bundle..."
          flatpak build-bundle \
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
            repo ../StreamingServiceLauncher_v${VERSION}.flatpak $APP_ID || {
            
            # As a last resort, create a simple tarball as a Flatpak substitute
            echo "Bundle creation failed, creating tarball in Flatpak format..."
            cd build-dir
            tar czf ../../StreamingServiceLauncher_v${VERSION}.flatpak files/
            cd ../..
          }
          
          # Check if bundle was created and make executable
          if [ -f "StreamingServiceLauncher_v${VERSION}.flatpak" ]; then
            chmod +x StreamingServiceLauncher_v${VERSION}.flatpak
            echo "Flatpak bundle created successfully"
            ls -la StreamingServiceLauncher_v${VERSION}.flatpak
            
            # Check if it's a real Flatpak or just a placeholder
            FILE_SIZE=$(stat -c%s StreamingServiceLauncher_v${VERSION}.flatpak 2>/dev/null || stat -f%z StreamingServiceLauncher_v${VERSION}.flatpak)
            if [ "$FILE_SIZE" -lt 1000000 ]; then
              echo "Warning: File appears to be too small to be a proper Flatpak"
            else
              echo "File size looks reasonable (${FILE_SIZE} bytes)"
            fi
          else
            echo "Failed to create bundle file, creating placeholder"
            echo "This is a placeholder file. Actual build failed." > StreamingServiceLauncher_v${VERSION}.flatpak
          fi
        continue-on-error: true

      - name: show files and verify output
        run: |
          echo "=== AppImage build results: ==="
          ls -la ./dist/StreamingServiceLauncher_v*_linux.AppImage || echo "No AppImage found"
          
          echo "=== Flatpak build results: ==="
          ls -la ./StreamingServiceLauncher_v*.flatpak || echo "No Flatpak found"
          
          echo "=== Build directory structure (if exists): ==="
          ls -la ./flatpak/build-dir/ || echo "Build directory not found"
          
          echo "=== Debugging info: ==="
          # Check file sizes to verify if we got a real Flatpak or just a placeholder
          if [ -f $(ls StreamingServiceLauncher_v*.flatpak 2>/dev/null) ]; then
            FLATPAK_SIZE=$(du -h $(ls StreamingServiceLauncher_v*.flatpak) | cut -f1)
            echo "Flatpak size: $FLATPAK_SIZE"
            
            # Check if it appears to be a real Flatpak (should be several MB at least)
            FILE_SIZE=$(stat -c%s StreamingServiceLauncher_v*.flatpak 2>/dev/null || stat -f%z StreamingServiceLauncher_v*.flatpak)
            if [ "$FILE_SIZE" -lt 1000000 ]; then
              echo "WARNING: Flatpak file appears to be too small - likely a placeholder or incomplete build"
            else
              echo "Flatpak size looks reasonable ($FILE_SIZE bytes), build likely succeeded"
            fi
          fi
          
          # Capture build logs for artifacts
          mkdir -p build-logs
          echo "Saving build logs for debugging..."
          cp -r flatpak/build-dir/.flatpak-builder/build.log build-logs/ 2>/dev/null || echo "No build log found"
          cp -r flatpak/build-dir/.flatpak-builder/rofiles build-logs/ 2>/dev/null || echo "No rofiles directory found" 
          find flatpak -name "*.log" -exec cp {} build-logs/ \; 2>/dev/null || echo "No additional logs found"
      
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-build-logs
          path: build-logs/
          retention-days: 7
          if-no-files-found: ignore
          
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-build
          path: dist/*.AppImage
          retention-days: 7
          if-no-files-found: warn
          
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-build
          path: StreamingServiceLauncher_v*.flatpak
          retention-days: 7
          if-no-files-found: warn
          
  create_release:
    needs: build_linux
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Upload AppImage Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Fix the path to match the artifact name and remove double v
          asset_path: appimage-build/StreamingServiceLauncher_${{ github.ref_name }}_linux.AppImage
          asset_name: StreamingServiceLauncher_${{ github.ref_name }}_linux.AppImage
          asset_content_type: application/octet-stream
          
      - name: Upload Flatpak Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Fix the path to match the artifact name and remove double v
          asset_path: flatpak-build/StreamingServiceLauncher_${{ github.ref_name }}.flatpak
          asset_name: StreamingServiceLauncher_${{ github.ref_name }}.flatpak
          asset_content_type: application/octet-stream

      - name: Publish AppImage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StreamingServiceLauncher-AppImage
          path: ./dist/StreamingServiceLauncher_v*_linux.AppImage
          if-no-files-found: warn
          
      - name: Publish Flatpak Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StreamingServiceLauncher-Flatpak
          path: ./StreamingServiceLauncher_v*.flatpak
          if-no-files-found: warn

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: publish to github release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/StreamingServiceLauncher-AppImage/*
            artifacts/StreamingServiceLauncher-Flatpak/*
          tag_name: ${{ github.ref_name }}
          body: |
            StreamingServiceLauncher Release
          draft: true
          generate_release_notes: true
          prerelease: contains(github.ref, 'pre')
        env:
          GITHUB_TOKEN: ${{ github.token }}
